---
name: Publish GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.8.0

      - name: Setup Python environment
        run: |
          devbox run -- poetry install

      - name: Build and deploy docs
        run: |
          devbox run -- poetry run mkdocs gh-deploy --force --no-history --remote-branch gh-pages
