name: Publish T&C Tech Docs
on:
  workflow_dispatch:
  push:
    paths:
      - "docs/**"
    branches:
      - main

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow LF-Engineering/tc-tech-docs
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: LF-Engineering/tc-tech-docs
          workflow: publish-docs.yml
          ref: main
          token: "${{ secrets.GH_TOKEN_TC_TECH_DOCS }}"
